spring:
  mail:
    default-encoding: UTF-8
    host: smtp.office365.com
    port: 587
    password: xxxxx
    username: g867030436@outlook.com
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true #授权
          starttls:
            enable: true
            required: true
  freemarker:
    suffix: .html
    request-context-attribute: request
    charset: UTF-8

microsof-tgraph:
  appId: a939a265-6aa7-469e-8b7a-2b3285336735
  appPassword: -:jRe*SQW2C[kqBRpPmAY3uahHR0EwB3
  redirectUrl: http://localhost:8080/authorize
